[tool.poetry]
name = "mt5linux"
version = "0.2.0"
description = "MetaTrader5 for linux users"
readme = "README.md"
authors = ["Lucas Prett Campagna https://github.com/lucas-campagna/mt5linux"]

[tool.poetry.dependencies]
python = ">=3.7"
numpy = "1.21.4"
rpyc = "^5.2.3"
pyparsing = "2.4.7"
MetaTrader5 = { version = "*", markers = "sys_platform == 'Windows'" }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^7.1.2" 

[build-system]
requires = [
    "setuptools>=64", 
    "poetry-core>=1.9.0",
    "toml>=0.10.2",
]
build-backend = "poetry.core.masonry.api"
