apiVersion: v1
kind: Service
metadata:
  name: trade-flow
spec:
  selector:
    app: trade-flow
  ports:
    - name: server
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-flow
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: trade-flow
  template:
    metadata:
      labels:
        app: trade-flow
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: trade-flow
          image: {{ .Values.images.trade-flow }}
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.trade-flow.DATABASE_URL }}"
