version: '3.5'

services:
  postgres:
    container_name: tradeflow-database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DATABASE: tradeflow
      PGDATA: /data/postgres
    volumes:
      - tradeflow-database:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - tradeflow-network
    restart: unless-stopped

  pgadmin:
    container_name: tradeflow-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - tradeflow-network
    restart: unless-stopped

  redis:
    container_name: tradeflow-redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - tradeflow-network

networks:
  tradeflow-network:

volumes:
  tradeflow-database:
  pgadmin:
