[environment]
name = "gym_anytrading"
version = "0.1.0"
description = "`AnyTrading` is a collection of [OpenAI Gym](https://github.com/openai/gym) environments for reinforcement learning-based trading algorithms."
type = "train"
engine = "gym"
url = "https://github.com/AminHP/gym-anytrading"
