name: TradeFlow CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          bash scripts/install-talib.sh
      - name: Install package
        run: |
          pip install -e .
      - name: Test
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q tests/
      - name: Lint with flake8
        run: |
          conda install -c conda-forge flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
