name: Docker Environment Pipeline

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docker-images:
    name: build-docker-images
    runs-on: ubuntu-latest
    env:
      BUILD_MODE: release

    steps:
      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: false
          haskell: false
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8.0.1

      - name: Build trade_flow image (latest)
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        id: docker_build_environment_latest
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/trade_flow:latest
          cache-from: type=gha
          cache-to: type=gha
      - name: Digest trade_flow image
        run: echo ${{ steps.docker_build_environment_latest.outputs.digest }}
